/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import javax.swing.DefaultListModel;
import java.io.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Kaushe
 */
public class addmovies extends javax.swing.JFrame {

    String filepath = null;
    int s = 0;
    byte[] photo;

    /**
     * Creates new form addmovies
     */
    public addmovies() {
        setTitle("Movie Details");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        ViewTable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        MovieName = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Movie ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 90, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Image ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Movie Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Price ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Year");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 40, -1));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 27, 195, -1));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 59, 195, -1));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 91, 195, -1));

        jTextField4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 123, 195, -1));

        jTextField5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 161, 195, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Lead");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 197, 50, 30));

        jTextField6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 199, 195, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("Genre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 235, -1, 30));

        jTextField7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 237, 195, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setText("Duration");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 273, -1, 30));

        jTextField8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 275, 195, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel9.setText("Rating");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 313, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel10.setText("Added By");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 343, -1, 30));

        jTextField9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 307, 195, -1));

        jTextField10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 345, 195, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel11.setText("Total");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 383, 60, 30));

        jTextField11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 383, 195, -1));

        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 300, 270));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 230, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel13.setText("Available");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 419, -1, 30));

        jTextField13.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 421, 205, -1));

        Back.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        Clear.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, -1));

        Add.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, -1, -1));

        ViewTable.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ViewTable.setText("View Table");
        ViewTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTableActionPerformed(evt);
            }
        });
        getContentPane().add(ViewTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, -1, -1));

        jList1.setModel(new DefaultListModel ());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 27, 242, 414));

        MovieName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        MovieName.setText("Movie Name");
        MovieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieNameActionPerformed(evt);
            }
        });
        getContentPane().add(MovieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, -1, -1));

        Update.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 470, -1, -1));

        Delete.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 470, -1, -1));

        Search.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 80, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Divvya\\Desktop\\images\\neww.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1110, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filepath = f.getAbsolutePath();
        jTextField12.setText(filepath);

        ImageIcon img = new ImageIcon(f.getAbsolutePath());
        Rectangle rectangle_img = jLabel12.getBounds();
        Image scaledImage = img.getImage().getScaledInstance(rectangle_img.width, rectangle_img.height, Image.SCALE_DEFAULT);
        img = new ImageIcon(scaledImage);
        jLabel12.setIcon(img);

        try {
            File photo = new File(filepath);
            FileInputStream fis = new FileInputStream(photo);
            ByteArrayOutputStream byte_photo = new ByteArrayOutputStream();
            byte[] buffer = new byte[1024];
            for (int readnumber; (readnumber = fis.read(buffer)) != -1;) {
                byte_photo.write(buffer, 0, readnumber);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        photo = byte_photo.toByteArray();
    }//GEN-LAST:event_SearchActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        welcome welc = new welcome();
        welc.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField13.setText("");
        jList1.clearSelection();

    }//GEN-LAST:event_ClearActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        try {
            String movieID = jTextField1.getText();
            String imageID = jTextField2.getText();
            String moviename = jTextField3.getText();
            String price = jTextField4.getText();
            String year = jTextField5.getText();
            String lead = jTextField6.getText();
            String genre = jTextField7.getText();
            String duration = jTextField8.getText();
            String rating = jTextField9.getText();
            String Addedby = jTextField10.getText();
            String total = jTextField11.getText();
            String available = jTextField13.getText();

            Connection c = DB.getConnect();
            String query;
            query = "insert into movie (movieID,imgId,name,price,year,lead,genre,duration,rating,addedBy,total,available,image) values (?,?,?,?,?,?,?,?,?,?,?,?,?)";

            if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField2.getText().isEmpty()
                    || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty()
                    || jTextField6.getText().isEmpty() || jTextField7.getText().isEmpty() || jTextField8.getText().isEmpty()
                    || jTextField9.getText().isEmpty() || jTextField10.getText().isEmpty() || jTextField11.getText().isEmpty()
                    || jTextField12.getText().isEmpty() || jTextField13.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "One of the required field is empty!", "Error", JOptionPane.ERROR_MESSAGE);
               
                
            } else {

                PreparedStatement statement = c.prepareStatement(query);
                statement.setString(1, movieID);
                statement.setString(2, imageID);
                statement.setString(3, moviename);
                statement.setString(4, price);
                statement.setString(5, year);
                statement.setString(6, lead);
                statement.setString(7, genre);
                statement.setString(8, duration);
                statement.setString(9, rating);
                statement.setString(10, Addedby);
                statement.setString(11, total);
                statement.setString(12, available);
                statement.setBytes(13, photo);

                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(null, "New movie has been added to the system");

                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void ViewTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTableActionPerformed
        // TODO add your handling code here:

        movietable mv = new movietable();
        mv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViewTableActionPerformed

    private void MovieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieNameActionPerformed
        // TODO add your handling code here:
        DefaultListModel list = (DefaultListModel) jList1.getModel();
        String sql5 = "Select * from movie";
        try {
           Connection con= DB.getConnect();
          Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql5);
            while (rs.next()) {
                String no = rs.getString("name");
                list.addElement(no);
            }
            jList1.setModel(list);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_MovieNameActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        try {
          Connection con = DB.getConnect();
          Statement stmt = con.createStatement();
            String num = (String) jList1.getSelectedValue();
            String sql6 = "Select * from movie where name = '" + (num) + "'";
            ResultSet rs = stmt.executeQuery(sql6);
            while (rs.next()) {
                String id1 = rs.getString("movieID");
                String imgid = rs.getString("imgID");
                String name1 = rs.getString("name");
                String price1 = rs.getString("price");
                String yr = rs.getString("year");
                String lead1 = rs.getString("lead");
                String gen = rs.getString("genre");
                String dur = rs.getString("duration");
                String rat = rs.getString("rating");
                String ad = rs.getString("addedBy");
                String tot = rs.getString("total");
                String avai = rs.getString("available");

                jTextField1.setText(id1);
                jTextField2.setText(imgid);
                jTextField3.setText(name1);
                jTextField4.setText(price1);
                jTextField5.setText(yr);
                jTextField6.setText(lead1);
                jTextField7.setText(gen);
                jTextField8.setText(dur);
                jTextField9.setText(rat);
                jTextField10.setText(ad);
                jTextField11.setText(tot);
                jTextField13.setText(avai);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jList1MouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DB.getConnect();
            Statement stmt = con.createStatement();
            String num1 = (String) jList1.getSelectedValue();
            String movid = jTextField1.getText();
            String img1 = jTextField2.getText();
            String nam = jTextField3.getText();
            String pric = jTextField4.getText();
            String yea = jTextField5.getText();
            String lea = jTextField6.getText();
            String ge = jTextField7.getText();
            String du = jTextField8.getText();
            String ra = jTextField9.getText();
            String add = jTextField10.getText();
            String tota = jTextField11.getText();
            String availa = jTextField13.getText();

            if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField2.getText().isEmpty()
                    || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty()
                    || jTextField6.getText().isEmpty() || jTextField7.getText().isEmpty() || jTextField8.getText().isEmpty()
                    || jTextField9.getText().isEmpty() || jTextField10.getText().isEmpty() || jTextField11.getText().isEmpty()
                    || jTextField12.getText().isEmpty() || jTextField13.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "One of the required field is empty!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String sql7 = "Update movie set movieID='" + (movid) + "', imgId='" + (img1) + "', name='" + (nam) + "', price='" + (pric) + "',year='" + (yea) + "', lead='" + (lea) + "', genre='" + (ge) + "', duration='" + (du) + "', rating='" + (ra) + "', addedBy='" + (add) + "', total='" + (tota) + "', available='" + (availa) + "' where name = '" + (num1) + "'";
                JOptionPane.showMessageDialog(null, "Table MOVIE updated!!!");

                stmt.executeUpdate(sql7);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField11.setText("");
                jTextField13.setText("");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DB.getConnect();
            Statement stmt = con.createStatement();
            String nm = (String) jList1.getSelectedValue();
            
            if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField2.getText().isEmpty()
                    || jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty()
                    || jTextField6.getText().isEmpty() || jTextField7.getText().isEmpty() || jTextField8.getText().isEmpty()
                    || jTextField9.getText().isEmpty() || jTextField10.getText().isEmpty() || jTextField11.getText().isEmpty()
                    || jTextField12.getText().isEmpty() || jTextField13.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "One of the required field is empty!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {

            String sql2 = "Delete from movie where name = '" + (nm) + "'";
            stmt.executeUpdate(sql2);
            JOptionPane.showMessageDialog(null, "Row deleted from the database!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addmovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addmovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addmovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addmovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addmovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Back;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton MovieName;
    private javax.swing.JButton Search;
    private javax.swing.JButton Update;
    private javax.swing.JButton ViewTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private static class byte_photo {

        private static byte[] toByteArray() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public byte_photo() {
        }
    }
}
