package admin;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SHAHIK
 */
public class customertable extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public customertable() {
        Connection c = DB.getConnect();
        initComponents();
        this.setLocationRelativeTo(null);
        //viewtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cTable = new javax.swing.JTable();
        viewT = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cTable.setAutoCreateRowSorter(true);
        cTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "customerId", "fname", "lname", "nic", "address", "contact", "payType", "accType", "regDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        cTable.setRequestFocusEnabled(false);
        cTable.setRowHeight(20);
        jScrollPane1.setViewportView(cTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 843, 210));

        viewT.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        viewT.setText("View");
        viewT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTActionPerformed(evt);
            }
        });
        getContentPane().add(viewT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 292, 94, 40));

        back.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 97, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Divvya\\Desktop\\images\\neww.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void viewtable () {
        
       
       
        try {
       
         Connection c = DB.getConnect();
         Statement stmt = c.createStatement();
        
      
         String Querey = "SELECT * FROM customer";
         ResultSet rs = stmt.executeQuery(Querey);
        
      
        while (rs.next()) {
        
            String customerId= rs.getString("customerId");
            String fname= rs.getString("fname");
            String lname= rs.getString("lname");
            String nic= rs.getString("nic");
            String address= rs.getString("address");
            String contact= rs.getString("contact");
            String payType= rs.getString("payType");
            String accType= rs.getString("accType");
            String regDate= rs.getString("regDate");
           
            DefaultTableModel model=(DefaultTableModel) cTable.getModel();
            model.addRow(new Object []{
               customerId,fname,lname,nic,address,contact,payType,accType,regDate});
             
                     
        }
           
        }
        
               catch (SQLException ex)
     {
         JOptionPane.showMessageDialog(this, ex.getMessage());
     
     }
    
    }  
    private void viewTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTActionPerformed
            viewtable ();
            
    }//GEN-LAST:event_viewTActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        Customer cus = new Customer();
        cus.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customertable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customertable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customertable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customertable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customertable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTable cTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewT;
    // End of variables declaration//GEN-END:variables

    class cid {

        public cid() {
        }
    }
}
