/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Divvya
 */
public class reports extends javax.swing.JFrame {

    /**
     * Creates new form reports
     */
    public reports() {
         setTitle("Reports");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminReport = new javax.swing.JButton();
        MovieReport = new javax.swing.JButton();
        CustomerReport = new javax.swing.JButton();
        TransactionReport = new javax.swing.JButton();
        UserReqReport = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminReport.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        adminReport.setText("Admin Report");
        adminReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminReportActionPerformed(evt);
            }
        });
        getContentPane().add(adminReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 63, 301, 30));

        MovieReport.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        MovieReport.setText("Movie Report");
        MovieReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieReportActionPerformed(evt);
            }
        });
        getContentPane().add(MovieReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 301, -1));

        CustomerReport.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        CustomerReport.setText("Customer Report");
        CustomerReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerReportActionPerformed(evt);
            }
        });
        getContentPane().add(CustomerReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 301, -1));

        TransactionReport.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        TransactionReport.setText("Transaction Report");
        TransactionReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionReportActionPerformed(evt);
            }
        });
        getContentPane().add(TransactionReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 301, -1));

        UserReqReport.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        UserReqReport.setText("User Requests Report");
        UserReqReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserReqReportActionPerformed(evt);
            }
        });
        getContentPane().add(UserReqReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 301, -1));

        Back.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Divvya\\Desktop\\images\\oOEwHu6.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        welcome welc = new welcome();
        welc.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void TransactionReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionReportActionPerformed
try {

            reportCall rep = new reportCall("C:\\Users\\Divvya\\Desktop\\New folder (3)\\Video Lending\\transactionReport.jasper");
        } catch (JRException ex) {
            Logger.getLogger(TRANS_detils.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TransactionReportActionPerformed

    private void MovieReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieReportActionPerformed
        // TODO add your handling code here:
        try {

            reportCall rep = new reportCall("C:\\Users\\Divvya\\Desktop\\New folder (3)\\Video Lending\\movieReport2.jasper");
        } catch (JRException ex) {
            Logger.getLogger(TRANS_detils.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MovieReportActionPerformed

    private void adminReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminReportActionPerformed
        try {

            reportCall rep = new reportCall("C:\\Users\\Divvya\\Desktop\\New folder (3)\\Video Lending\\adminreport2.jasper");
        } catch (JRException ex) {
            Logger.getLogger(TRANS_detils.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adminReportActionPerformed

    private void CustomerReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerReportActionPerformed
         try {

            reportCall rep = new reportCall("C:\\Users\\Divvya\\Desktop\\New folder (3)\\Video Lending\\customerReport.jasper");
        } catch (JRException ex) {
            Logger.getLogger(TRANS_detils.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CustomerReportActionPerformed

    private void UserReqReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserReqReportActionPerformed
        try {

            reportCall rep = new reportCall("C:\\Users\\Divvya\\Desktop\\New folder (3)\\Video Lending\\UserReqReport.jasper");
        } catch (JRException ex) {
            Logger.getLogger(TRANS_detils.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UserReqReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton CustomerReport;
    private javax.swing.JButton MovieReport;
    private javax.swing.JButton TransactionReport;
    private javax.swing.JButton UserReqReport;
    private javax.swing.JButton adminReport;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
